server:
    port: 8081
spring:
    datasource:
        url: jdbc:h2:mem:graphql
        username : username
        password : password
        driver-class-name : org.h2.Driver

    jpa:
        database: H2
        show-sql: false
        open-in-view: false
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate.dialect: org.hibernate.dialect.H2Dialect
            hibernate.hbm2ddl.auto:
    h2:
        console:
            enabled: true
            settings:
                trace: true





